# Generated by Django 2.1.5 on 2019-01-10 18:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import qapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bogie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('manufactured_date', models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2019)])),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 47, 6, 539821))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=qapp.models.UploadToPathAndRename('/home/mati/pydev/dzj/media/uploads_c'))),
                ('file_rel_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BJC', 'Bramka jakościowa - człon'), ('BJW', 'Bramka jakościowa - wózek'), ('IKS', 'Inspekcja końcowa - Solaris'), ('IKK', 'Inspekcja końcowa - klient')], default='BJC', max_length=3)),
                ('bogie_type', models.CharField(choices=[('WN1', 'Wózek napędowy 1'), ('WN2', 'Wózek napędowy 2'), ('WT', 'Wózek toczny'), ('WN3', 'Wózek napędowy 3'), ('WN4', 'Wózek napędowy 4')], max_length=3, null=True)),
                ('car', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], max_length=2, null=True)),
                ('operation_no', models.CharField(max_length=6, null=True)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('gate_status', models.CharField(choices=[('R', 'Realizacja'), ('O', 'Ocena DZJ'), ('P', 'Ponowna realizacja'), ('A', 'Archiwum')], default='R', max_length=1)),
                ('gate_rating', models.CharField(blank=True, choices=[('OK', 'Zaakceptowany'), ('NOK', 'Odrzucony')], max_length=3)),
                ('reject_counter', models.IntegerField(default='0')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 19, 47, 6, 538803))),
                ('modify_date', models.DateTimeField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ('-tram',),
                'permissions': (('can_change_gate_status', 'Może zmenić status bramki'), ('can_change_gate_rating', 'Może zmienić ocenę bramki'), ('can_add_new_gate', 'Może dodać nową bramkę')),
            },
        ),
        migrations.CreateModel(
            name='GateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads_g')),
                ('file_rel_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 47, 6, 540571))),
                ('category', models.CharField(blank=True, max_length=1)),
                ('action', models.CharField(max_length=30)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log_rel_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate')),
            ],
        ),
        migrations.CreateModel(
            name='OperationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('KLE', 'Klejownia'), ('KAB', 'Kablownia'), ('PDM', 'Podmontaż dachów - mechanika'), ('PDE', 'Podmontaż dachów - elektryka'), ('MGM', 'Montaż główny - mechanika'), ('MGE', 'Montaż główny - elektryka'), ('MKM', 'Montaż końcowy - mechanika'), ('MKE', 'Montaż końcowy - elektryka'), ('MWM', 'Montaż wózków - mechanika'), ('MWE', 'Montaż wózków - elektryka'), ('MKA', 'Montaż kabin'), ('TES', 'Testing'), ('MWM', 'Montaż wózków - mechanika'), ('MWE', 'Montaż wózków - elektryka'), ('ISD', 'Inspekcja końcowa Solaris - dach'), ('ISP', 'Inspekcja końcowa Solaris - podwozie'), ('ISW', 'Inspekcja końcowa Solaris - wnętrzne'), ('ISZ', 'Inspekcja końcowa Solaris - zewnątrz'), ('ISL', 'Inspekcja końcowa Solaris - lakier'), ('IKT', 'Inspekcja końcowa klienta - tramwaj')], max_length=3)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('manufactured_date', models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2019)])),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.OperationArea'),
        ),
        migrations.AddField(
            model_name='gate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gate',
            name='bogie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.Bogie'),
        ),
        migrations.AddField(
            model_name='gate',
            name='tram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.Tram'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_rel_gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate'),
        ),
    ]
