# Generated by Django 2.1.3 on 2018-12-15 12:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 12, 15, 13, 18, 17, 763993))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads_c')),
                ('file_rel_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], max_length=2)),
                ('operation_no', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('gate_status', models.CharField(choices=[('R', 'Realizacja'), ('O', 'Ocena DZJ'), ('P', 'Ponowna realizacja'), ('A', 'Archiwum')], default='R', max_length=1)),
                ('gate_rating', models.CharField(blank=True, choices=[('OK', 'Zaakceptowany'), ('NOK', 'Odrzucony')], max_length=3)),
                ('reject_counter', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ('-tram',),
                'permissions': (('can_change_gate_status', 'Może zmenić status bramki'), ('can_change_gate_rating', 'Może zmienić ocenę bramki'), ('can_add_new_gate', 'Może dodać nową bramkę')),
            },
        ),
        migrations.CreateModel(
            name='GateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads_g')),
                ('file_rel_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=18)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2018, 12, 15, 13, 18, 17, 764993))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log_rel_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate')),
            ],
        ),
        migrations.CreateModel(
            name='OperationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('KLE', 'Klejownia'), ('KAB', 'Kablownia'), ('PDM', 'Podmontaż dachów - mechanika'), ('PDE', 'Podmontaż dachów - elektryka'), ('MGM', 'Montaż główny - mechanika'), ('MGE', 'Montaż główny - elektryka'), ('MKM', 'Montaż końcowy - mechanika'), ('MKE', 'Montaż końcowy - elektryka'), ('MWM', 'Montaż wózków - mechanika'), ('MWE', 'Montaż wózków - elektryka'), ('MKA', 'Montaż kabin'), ('TES', 'Testing')], max_length=3)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('manufactured_date', models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2018)])),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.OperationArea'),
        ),
        migrations.AddField(
            model_name='gate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gate',
            name='tram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.Tram'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_rel_gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Gate'),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('tram', 'car', 'area', 'operation_no')},
        ),
    ]
