# Generated by Django 2.1.3 on 2018-12-19 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0002_auto_20181218_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 19, 11, 3, 37, 177737)),
        ),
        migrations.AddField(
            model_name='gate',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 19, 11, 3, 37, 177737)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 3, 37, 178737)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 3, 37, 179738)),
        ),
    ]
