# Generated by Django 2.1.3 on 2018-12-19 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0003_auto_20181219_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 6, 17, 305507)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default='2018-12-19 11:06:17.304507'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='modify_date',
            field=models.DateTimeField(blank=True, default='2018-12-19 11:06:17.304507'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 6, 17, 306508)),
        ),
    ]
