# Generated by Django 2.1.3 on 2018-12-19 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0004_auto_20181219_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 34, 25, 648243)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default='2018-12-19 11:34:25.646244'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='modify_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 11, 34, 25, 650244)),
        ),
    ]
