# Generated by Django 2.1.3 on 2018-12-26 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0007_auto_20181219_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 15, 55, 34, 172794)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 26, 15, 55, 34, 170792)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 15, 55, 34, 174794)),
        ),
    ]
