# Generated by Django 2.1.3 on 2018-12-30 19:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0010_auto_20181230_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bogie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('manufactured_date', models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2018)])),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='gate',
            name='type',
            field=models.CharField(choices=[('P', 'Pojazd'), ('W', 'Wózek')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 54, 0, 606260)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 30, 20, 54, 0, 604259)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 54, 0, 608261)),
        ),
        migrations.AddField(
            model_name='gate',
            name='bogie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qapp.Bogie'),
        ),
    ]
