# Generated by Django 2.1.3 on 2018-12-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0011_auto_20181230_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate',
            old_name='type',
            new_name='gate_type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 58, 2, 602744)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 30, 20, 58, 2, 598742)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 20, 58, 2, 604744)),
        ),
    ]
