# Generated by Django 2.1.3 on 2018-12-30 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0013_auto_20181230_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='gate_type',
        ),
        migrations.AddField(
            model_name='gate',
            name='type',
            field=models.CharField(choices=[('P', 'Pojazd'), ('W', 'Wózek')], default='P', max_length=6),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 1, 38, 446607)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 30, 21, 1, 38, 444606)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 1, 38, 448605)),
        ),
    ]
