# Generated by Django 2.1.3 on 2018-12-30 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0014_auto_20181230_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 3, 42, 557319)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 30, 21, 3, 42, 554316)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='type',
            field=models.CharField(choices=[('P', 'Pojazd'), ('W', 'Wózek')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 3, 42, 558319)),
        ),
    ]
