# Generated by Django 2.1.3 on 2018-12-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0015_auto_20181230_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 4, 59, 476922)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 30, 21, 4, 59, 471906)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='type',
            field=models.CharField(choices=[('P', 'Pojazd'), ('W', 'Wózek')], default='P', max_length=6),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 4, 59, 480925)),
        ),
    ]
