# Generated by Django 2.1.3 on 2018-12-30 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0018_auto_20181231_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 0, 38, 27, 104845)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 0, 38, 27, 103844)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 0, 38, 27, 105846)),
        ),
    ]
