# Generated by Django 2.1.3 on 2018-12-30 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0019_auto_20181231_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='type',
            field=models.CharField(choices=[('BJC', 'Bramka jakościowa - człon'), ('BJW', 'Bramka jakościowa - wózek'), ('IKS', 'Inspekcja końcowa - Solaris'), ('IKK', 'Inspekcja końcowa - klient')], default='BJC', max_length=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 0, 38, 44, 601973)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 0, 38, 44, 600972)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 0, 38, 44, 602974)),
        ),
    ]
