# Generated by Django 2.1.3 on 2018-12-31 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0020_auto_20181231_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='bogie_type',
            field=models.CharField(choices=[('WN1', 'Wózek napędowy 1'), ('WN2', 'Wózek napędowy 2'), ('WT', 'Wózek toczny'), ('WN3', 'Wózek napędowy 3'), ('WN4', 'Wózek napędowy 4')], default='WN1', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 1, 3, 47, 264530)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 1, 3, 47, 263529)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 1, 3, 47, 265531)),
        ),
        migrations.AlterField(
            model_name='operationarea',
            name='area',
            field=models.CharField(choices=[('KLE', 'Klejownia'), ('KAB', 'Kablownia'), ('PDM', 'Podmontaż dachów - mechanika'), ('PDE', 'Podmontaż dachów - elektryka'), ('MGM', 'Montaż główny - mechanika'), ('MGE', 'Montaż główny - elektryka'), ('MKM', 'Montaż końcowy - mechanika'), ('MKE', 'Montaż końcowy - elektryka'), ('MWM', 'Montaż wózków - mechanika'), ('MWE', 'Montaż wózków - elektryka'), ('MKA', 'Montaż kabin'), ('TES', 'Testing'), ('MWM', 'Montaż wózków - mechanika'), ('MWE', 'Montaż wózków - elektryka'), ('ISD', 'Inspekcja końcowa Solaris - dach'), ('ISP', 'Inspekcja końcowa Solaris - podwozie'), ('ISW', 'Inspekcja końcowa Solaris - wnętrzne'), ('ISZ', 'Inspekcja końcowa Solaris - zewnątrz'), ('ISL', 'Inspekcja końcowa Solaris - lakier'), ('IKT', 'Inspekcja końcowa klienta - tramwaj')], max_length=3),
        ),
    ]
