# Generated by Django 2.1.3 on 2018-12-31 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0026_auto_20181231_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 22, 37, 210551)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 12, 22, 37, 209551)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 22, 37, 211551)),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('tram', 'car', 'area', 'operation_no')},
        ),
    ]
