# Generated by Django 2.1.3 on 2018-12-31 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0027_auto_20181231_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 23, 33, 377486)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 12, 23, 33, 376485)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 23, 33, 378487)),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('type', 'tram', 'car', 'area', 'operation_no')},
        ),
    ]
