# Generated by Django 2.1.3 on 2018-12-31 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0028_auto_20181231_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 25, 1, 833155)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 12, 25, 1, 832154)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 12, 25, 1, 834155)),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('type', 'tram', 'bogie', 'car', 'area', 'operation_no')},
        ),
    ]
