# Generated by Django 2.1.3 on 2018-12-31 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0029_auto_20181231_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 13, 30, 39, 647903)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 13, 30, 39, 645910)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 13, 30, 39, 648903)),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together=set(),
        ),
    ]
