# Generated by Django 2.1.3 on 2019-01-05 17:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0030_auto_20181231_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogie',
            name='manufactured_date',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2019)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 18, 38, 55, 27267)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 5, 18, 38, 55, 26267)),
        ),
        migrations.AlterField(
            model_name='gate',
            name='operation_no',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 18, 38, 55, 28268)),
        ),
        migrations.AlterField(
            model_name='tram',
            name='manufactured_date',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
